# Generated by Django 2.0 on 2017-12-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试中心',
                'verbose_name_plural': '考试中心',
            },
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('total', models.CharField(blank=True, max_length=128, null=True)),
                ('shui', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
        migrations.CreateModel(
            name='ExamOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=128, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试办',
                'verbose_name_plural': '考试办',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学校端',
                'verbose_name_plural': '学校端',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('idcard', models.CharField(blank=True, max_length=256, null=True)),
                ('bankcard', models.CharField(blank=True, max_length=256, null=True)),
                ('bankinfo', models.TextField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.School')),
            ],
            options={
                'verbose_name': '教师列表',
                'verbose_name_plural': '教师列表',
            },
        ),
        migrations.AddField(
            model_name='examinfo',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.ExamOffice'),
        ),
        migrations.AddField(
            model_name='examinfo',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='exam.Teacher'),
        ),
    ]
