# Generated by Django 2.0 on 2017-12-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_squashed_0011_auto_20171223_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': '中心', 'verbose_name_plural': '中心'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '考试', 'verbose_name_plural': '考试'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': '考办', 'verbose_name_plural': '考办'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='schoolexam',
            options={'verbose_name': '考点考试', 'verbose_name_plural': '考点考试'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-create_time', '-update_time'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AlterModelOptions(
            name='teacherexam',
            options={'verbose_name': '监考考试', 'verbose_name_plural': '监考考试'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', '通过'), ('checking', '审核中'), ('uncheck', '未审核')], max_length=128, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='schoolexam',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', '通过'), ('checking', '审核中'), ('uncheck', '未审核')], max_length=128, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='teacherexam',
            name='schoolexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Schoolexam', verbose_name='在某学校的考试'),
        ),
    ]
