# Generated by Django 2.0 on 2017-12-04 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamOffice',
            new_name='Office',
        ),
    ]
