# Generated by Django 2.0 on 2017-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20171204_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinfo',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='shui',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='starttime',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='school',
            field=models.ManyToManyField(to='exam.School'),
        ),
        migrations.AddField(
            model_name='examinfo',
            name='time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='teacher',
            field=models.ManyToManyField(to='exam.Teacher'),
        ),
    ]
