# Generated by Django 2.0 on 2017-12-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20171205_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True, null=True)),
                ('total', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.TextField()),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Office')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
        migrations.CreateModel(
            name='SchoolExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, max_length=256, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.School')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, max_length=256, null=True)),
                ('schoolexam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.SchoolExam')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='office',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='school',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ExamInfo',
        ),
    ]
