# Generated by Django 2.0 on 2017-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20171205_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolexam',
            options={'verbose_name': '考试办分配给学校的考试', 'verbose_name_plural': '考试办分配给学校的考试'},
        ),
        migrations.AlterModelOptions(
            name='teacherexam',
            options={'verbose_name': '学校分配给老师的考试', 'verbose_name_plural': '学校分配给老师的考试'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
