# Generated by Django 2.0 on 2017-12-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20171223_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(blank=True, choices=[(0, '通过'), (1, '审核中'), (2, '未审核')], max_length=128, null=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='status',
            field=models.CharField(blank=True, choices=[(0, '通过'), (1, '审核中'), (2, '未审核')], max_length=128, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='teacherexam',
            name='schoolexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Schoolexam', verbose_name='在某学校的考试'),
        ),
    ]
